vx2paraview: vx2paraview.cc
	g++ -O3 -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2paraview.cc -lz -o vx2paraview
debug: vx2paraview.cc
	g++ -O0 -g -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2paraview.cc -lz -o vx2paraview
