vx2refine: vx2refine.cc
	g++ -O3 -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2refine.cc -lz -o vx2refine
debug: vx2refine.cc
	g++ -O0 -g -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2refine.cc -lz -o vx2refine
