vx2ascii: vx2ascii.cc
	g++ -O3 -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2ascii.cc -lz -o vx2ascii
debug: vx2ascii.cc
	g++ -O0 -g -Wall -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -std=c++11 vx2ascii.cc -lz -o vx2ascii
