#gmy2hgb: gmy2inlets.cc
#	g++ -O3 -Wall gmy2inlets.cc -lz -o gmy2inlets
#debug: gmy2inlets.cc
#	g++ -g gmy2inlets.cc -lz -o gmy2inlets

gmy2hgb: gmy2lets.cc
	g++ -O3 -Wall gmy2lets.cc -lz -o gmy2lets -ltirpc
debug: gmy2lets.cc
	g++ -g gmy2lets.cc -lz -o gmy2lets -ltirpc
